package com.walden.mapper;

import com.walden.model.Cloth;
import com.walden.model.ClothCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ClothMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @SelectProvider(type=ClothSqlProvider.class, method="countByExample")
    long countByExample(ClothCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ClothSqlProvider.class, method="deleteByExample")
    int deleteByExample(ClothCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @Delete({
        "delete from Cloth",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Cloth (id, name, ",
        "from, picid, price)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{from,jdbcType=VARCHAR}, #{picid,jdbcType=VARCHAR}, #{price,jdbcType=VARCHAR})"
    })
    int insert(Cloth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @InsertProvider(type=ClothSqlProvider.class, method="insertSelective")
    int insertSelective(Cloth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @SelectProvider(type=ClothSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="from", property="from", jdbcType=JdbcType.VARCHAR),
        @Result(column="picid", property="picid", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.VARCHAR)
    })
    List<Cloth> selectByExample(ClothCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, from, picid, price",
        "from Cloth",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="from", property="from", jdbcType=JdbcType.VARCHAR),
        @Result(column="picid", property="picid", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.VARCHAR)
    })
    Cloth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ClothSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Cloth record, @Param("example") ClothCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ClothSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Cloth record, @Param("example") ClothCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ClothSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Cloth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Cloth
     *
     * @mbg.generated
     */
    @Update({
        "update Cloth",
        "set name = #{name,jdbcType=VARCHAR},",
          "from = #{from,jdbcType=VARCHAR},",
          "picid = #{picid,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Cloth record);
}